### ISSUE TITLE
Package: `games-arcade/osu-lazer-2021.820.0` fails to merge

### ISSUE THREAD

**Issue by m0lese** [m0lese/portage-overlay#46]
### Build Log

```shell
~ doas cat /var/tmp/portage/games-arcade/osu-lazer-2021.820.0/temp/build.log
 * Package:    games-arcade/osu-lazer-2021.820.0
 * Repository: molese
 * Maintainer: molese@protonmail.com
 * USE:        abi_x86_64 amd64 elibc_glibc kernel_linux userland_GNU
 * FEATURES:   preserve-libs sandbox userpriv usersandbox
>>> Unpacking source...
>>> Unpacking osu-lazer-2021.820.0.tar.gz to /var/tmp/portage/games-arcade/osu-lazer-2021.820.0/work
>>> Source unpacked in /var/tmp/portage/games-arcade/osu-lazer-2021.820.0/work
>>> Preparing source in /var/tmp/portage/games-arcade/osu-lazer-2021.820.0/work/osu-2021.820.0 ...
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/games-arcade/osu-lazer-2021.820.0/work/osu-2021.820.0 ...
>>> Source configured.
>>> Compiling source in /var/tmp/portage/games-arcade/osu-lazer-2021.820.0/work/osu-2021.820.0 ...

Welcome to .NET 5.0!
---------------------
SDK Version: 5.0.400

Telemetry
---------
The .NET tools collect usage data in order to help us improve your experience. It is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.

Read more about .NET CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry

----------------
Installed an ASP.NET Core HTTPS development certificate.
To trust the certificate run 'dotnet dev-certs https --trust' (Windows and macOS only).
Learn about HTTPS: https://aka.ms/dotnet-https
----------------
Write your first app: https://aka.ms/dotnet-hello-world
Find out what's new: https://aka.ms/dotnet-whats-new
Explore documentation: https://aka.ms/dotnet-docs
Report issues and find source on GitHub: https://github.com/dotnet/core
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli
--------------------------------------------------------------------------------------
Microsoft (R) Build Engine version 16.11.0+0538acc04 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Failed to download package 'System.IO.4.1.0' from 'https://api.nuget.org/v3-flatcontainer/system.io/4.1.0/system.io.4.1.0.nupkg'.
  The download of 'https://api.nuget.org/v3-flatcontainer/system.io/4.1.0/system.io.4.1.0.nupkg' timed out because no data was received for 60000ms.
    Exception of type 'System.TimeoutException' was thrown.
  Restored /var/tmp/portage/games-arcade/osu-lazer-2021.820.0/work/osu-2021.820.0/osu.Game.Rulesets.Mania/osu.Game.Rulesets.Mania.csproj (in 5.64 min).
  Restored /var/tmp/portage/games-arcade/osu-lazer-2021.820.0/work/osu-2021.820.0/osu.Game/osu.Game.csproj (in 5.64 min).
  Restored /var/tmp/portage/games-arcade/osu-lazer-2021.820.0/work/osu-2021.820.0/osu.Game.Rulesets.Catch/osu.Game.Rulesets.Catch.csproj (in 5.64 min).
  Restored /var/tmp/portage/games-arcade/osu-lazer-2021.820.0/work/osu-2021.820.0/osu.Game.Tournament/osu.Game.Tournament.csproj (in 5.64 min).
  Restored /var/tmp/portage/games-arcade/osu-lazer-2021.820.0/work/osu-2021.820.0/osu.Game.Rulesets.Osu/osu.Game.Rulesets.Osu.csproj (in 510 ms).
  Restored /var/tmp/portage/games-arcade/osu-lazer-2021.820.0/work/osu-2021.820.0/osu.Game.Rulesets.Taiko/osu.Game.Rulesets.Taiko.csproj (in 535 ms).
  Restored /var/tmp/portage/games-arcade/osu-lazer-2021.820.0/work/osu-2021.820.0/osu.Desktop/osu.Desktop.csproj (in 1.98 min).
  osu.Game -> /var/tmp/portage/games-arcade/osu-lazer-2021.820.0/work/osu-2021.820.0/osu.Game/bin/Release/netstandard2.1/osu.Game.dll
  osu.Game.Rulesets.Catch -> /var/tmp/portage/games-arcade/osu-lazer-2021.820.0/work/osu-2021.820.0/osu.Game.Rulesets.Catch/bin/Release/netstandard2.1/osu.Game.Rulesets.Catch.dll
  osu.Game.Rulesets.Mania -> /var/tmp/portage/games-arcade/osu-lazer-2021.820.0/work/osu-2021.820.0/osu.Game.Rulesets.Mania/bin/Release/netstandard2.1/osu.Game.Rulesets.Mania.dll
  osu.Game.Tournament -> /var/tmp/portage/games-arcade/osu-lazer-2021.820.0/work/osu-2021.820.0/osu.Game.Tournament/bin/Release/netstandard2.1/osu.Game.Tournament.dll
  osu.Game.Rulesets.Taiko -> /var/tmp/portage/games-arcade/osu-lazer-2021.820.0/work/osu-2021.820.0/osu.Game.Rulesets.Taiko/bin/Release/netstandard2.1/osu.Game.Rulesets.Taiko.dll
  osu.Game.Rulesets.Osu -> /var/tmp/portage/games-arcade/osu-lazer-2021.820.0/work/osu-2021.820.0/osu.Game.Rulesets.Osu/bin/Release/netstandard2.1/osu.Game.Rulesets.Osu.dll
/opt/dotnet_core/sdk/5.0.400/Microsoft.Common.CurrentVersion.targets(4679,5): warning MSB3026: Could not copy "/var/tmp/portage/games-arcade/osu-lazer-2021.820.0/homedir/.nuget/packages/ppy.osu.game.resources/2021.820.0/lib/netstandard2.1/pt-br/osu.Game.Resources.resources.dll" to "bin/Release/net5.0/linux-x64/pt-br/osu.Game.Resources.resources.dll". Beginning retry 1 in 1000ms. Could not find a part of the path '/var/tmp/portage/games-arcade/osu-lazer-2021.820.0/work/osu-2021.820.0/osu.Desktop/bin/Release/net5.0/linux-x64/pt-br/osu.Game.Resources.resources.dll'.  [/var/tmp/portage/games-arcade/osu-lazer-2021.820.0/work/osu-2021.820.0/osu.Desktop/osu.Desktop.csproj]
/opt/dotnet_core/sdk/5.0.400/Microsoft.Common.CurrentVersion.targets(4679,5): warning MSB3026: Could not copy "/var/tmp/portage/games-arcade/osu-lazer-2021.820.0/homedir/.nuget/packages/ppy.osu.game.resources/2021.820.0/lib/netstandard2.1/pt-br/osu.Game.Resources.resources.dll" to "bin/Release/net5.0/linux-x64/pt-br/osu.Game.Resources.resources.dll". Beginning retry 2 in 1000ms. Could not find a part of the path '/var/tmp/portage/games-arcade/osu-lazer-2021.820.0/work/osu-2021.820.0/osu.Desktop/bin/Release/net5.0/linux-x64/pt-br/osu.Game.Resources.resources.dll'.  [/var/tmp/portage/games-arcade/osu-lazer-2021.820.0/work/osu-2021.820.0/osu.Desktop/osu.Desktop.csproj]
/opt/dotnet_core/sdk/5.0.400/Microsoft.Common.CurrentVersion.targets(4679,5): warning MSB3026: Could not copy "/var/tmp/portage/games-arcade/osu-lazer-2021.820.0/homedir/.nuget/packages/ppy.osu.game.resources/2021.820.0/lib/netstandard2.1/pt-br/osu.Game.Resources.resources.dll" to "bin/Release/net5.0/linux-x64/pt-br/osu.Game.Resources.resources.dll". Beginning retry 3 in 1000ms. Could not find a part of the path '/var/tmp/portage/games-arcade/osu-lazer-2021.820.0/work/osu-2021.820.0/osu.Desktop/bin/Release/net5.0/linux-x64/pt-br/osu.Game.Resources.resources.dll'.  [/var/tmp/portage/games-arcade/osu-lazer-2021.820.0/work/osu-2021.820.0/osu.Desktop/osu.Desktop.csproj]
/opt/dotnet_core/sdk/5.0.400/Microsoft.Common.CurrentVersion.targets(4679,5): warning MSB3026: Could not copy "/var/tmp/portage/games-arcade/osu-lazer-2021.820.0/homedir/.nuget/packages/ppy.osu.game.resources/2021.820.0/lib/netstandard2.1/pt-br/osu.Game.Resources.resources.dll" to "bin/Release/net5.0/linux-x64/pt-br/osu.Game.Resources.resources.dll". Beginning retry 4 in 1000ms. Could not find a part of the path '/var/tmp/portage/games-arcade/osu-lazer-2021.820.0/work/osu-2021.820.0/osu.Desktop/bin/Release/net5.0/linux-x64/pt-br/osu.Game.Resources.resources.dll'.  [/var/tmp/portage/games-arcade/osu-lazer-2021.820.0/work/osu-2021.820.0/osu.Desktop/osu.Desktop.csproj]
/opt/dotnet_core/sdk/5.0.400/Microsoft.Common.CurrentVersion.targets(4679,5): warning MSB3026: Could not copy "/var/tmp/portage/games-arcade/osu-lazer-2021.820.0/homedir/.nuget/packages/ppy.osu.game.resources/2021.820.0/lib/netstandard2.1/pt-br/osu.Game.Resources.resources.dll" to "bin/Release/net5.0/linux-x64/pt-br/osu.Game.Resources.resources.dll". Beginning retry 5 in 1000ms. Could not find a part of the path '/var/tmp/portage/games-arcade/osu-lazer-2021.820.0/work/osu-2021.820.0/osu.Desktop/bin/Release/net5.0/linux-x64/pt-br/osu.Game.Resources.resources.dll'.  [/var/tmp/portage/games-arcade/osu-lazer-2021.820.0/work/osu-2021.820.0/osu.Desktop/osu.Desktop.csproj]
/opt/dotnet_core/sdk/5.0.400/Microsoft.Common.CurrentVersion.targets(4679,5): warning MSB3026: Could not copy "/var/tmp/portage/games-arcade/osu-lazer-2021.820.0/homedir/.nuget/packages/ppy.osu.game.resources/2021.820.0/lib/netstandard2.1/pt-br/osu.Game.Resources.resources.dll" to "bin/Release/net5.0/linux-x64/pt-br/osu.Game.Resources.resources.dll". Beginning retry 6 in 1000ms. Could not find a part of the path '/var/tmp/portage/games-arcade/osu-lazer-2021.820.0/work/osu-2021.820.0/osu.Desktop/bin/Release/net5.0/linux-x64/pt-br/osu.Game.Resources.resources.dll'.  [/var/tmp/portage/games-arcade/osu-lazer-2021.820.0/work/osu-2021.820.0/osu.Desktop/osu.Desktop.csproj]
/opt/dotnet_core/sdk/5.0.400/Microsoft.Common.CurrentVersion.targets(4679,5): warning MSB3026: Could not copy "/var/tmp/portage/games-arcade/osu-lazer-2021.820.0/homedir/.nuget/packages/ppy.osu.game.resources/2021.820.0/lib/netstandard2.1/pt-br/osu.Game.Resources.resources.dll" to "bin/Release/net5.0/linux-x64/pt-br/osu.Game.Resources.resources.dll". Beginning retry 7 in 1000ms. Could not find a part of the path '/var/tmp/portage/games-arcade/osu-lazer-2021.820.0/work/osu-2021.820.0/osu.Desktop/bin/Release/net5.0/linux-x64/pt-br/osu.Game.Resources.resources.dll'.  [/var/tmp/portage/games-arcade/osu-lazer-2021.820.0/work/osu-2021.820.0/osu.Desktop/osu.Desktop.csproj]
/opt/dotnet_core/sdk/5.0.400/Microsoft.Common.CurrentVersion.targets(4679,5): warning MSB3026: Could not copy "/var/tmp/portage/games-arcade/osu-lazer-2021.820.0/homedir/.nuget/packages/ppy.osu.game.resources/2021.820.0/lib/netstandard2.1/pt-br/osu.Game.Resources.resources.dll" to "bin/Release/net5.0/linux-x64/pt-br/osu.Game.Resources.resources.dll". Beginning retry 8 in 1000ms. Could not find a part of the path '/var/tmp/portage/games-arcade/osu-lazer-2021.820.0/work/osu-2021.820.0/osu.Desktop/bin/Release/net5.0/linux-x64/pt-br/osu.Game.Resources.resources.dll'.  [/var/tmp/portage/games-arcade/osu-lazer-2021.820.0/work/osu-2021.820.0/osu.Desktop/osu.Desktop.csproj]
/opt/dotnet_core/sdk/5.0.400/Microsoft.Common.CurrentVersion.targets(4679,5): warning MSB3026: Could not copy "/var/tmp/portage/games-arcade/osu-lazer-2021.820.0/homedir/.nuget/packages/ppy.osu.game.resources/2021.820.0/lib/netstandard2.1/pt-br/osu.Game.Resources.resources.dll" to "bin/Release/net5.0/linux-x64/pt-br/osu.Game.Resources.resources.dll". Beginning retry 9 in 1000ms. Could not find a part of the path '/var/tmp/portage/games-arcade/osu-lazer-2021.820.0/work/osu-2021.820.0/osu.Desktop/bin/Release/net5.0/linux-x64/pt-br/osu.Game.Resources.resources.dll'.  [/var/tmp/portage/games-arcade/osu-lazer-2021.820.0/work/osu-2021.820.0/osu.Desktop/osu.Desktop.csproj]
/opt/dotnet_core/sdk/5.0.400/Microsoft.Common.CurrentVersion.targets(4679,5): warning MSB3026: Could not copy "/var/tmp/portage/games-arcade/osu-lazer-2021.820.0/homedir/.nuget/packages/ppy.osu.game.resources/2021.820.0/lib/netstandard2.1/pt-br/osu.Game.Resources.resources.dll" to "bin/Release/net5.0/linux-x64/pt-br/osu.Game.Resources.resources.dll". Beginning retry 10 in 1000ms. Could not find a part of the path '/var/tmp/portage/games-arcade/osu-lazer-2021.820.0/work/osu-2021.820.0/osu.Desktop/bin/Release/net5.0/linux-x64/pt-br/osu.Game.Resources.resources.dll'.  [/var/tmp/portage/games-arcade/osu-lazer-2021.820.0/work/osu-2021.820.0/osu.Desktop/osu.Desktop.csproj]
/opt/dotnet_core/sdk/5.0.400/Microsoft.Common.CurrentVersion.targets(4679,5): error MSB3027: Could not copy "/var/tmp/portage/games-arcade/osu-lazer-2021.820.0/homedir/.nuget/packages/ppy.osu.game.resources/2021.820.0/lib/netstandard2.1/pt-br/osu.Game.Resources.resources.dll" to "bin/Release/net5.0/linux-x64/pt-br/osu.Game.Resources.resources.dll". Exceeded retry count of 10. Failed.  [/var/tmp/portage/games-arcade/osu-lazer-2021.820.0/work/osu-2021.820.0/osu.Desktop/osu.Desktop.csproj]
/opt/dotnet_core/sdk/5.0.400/Microsoft.Common.CurrentVersion.targets(4679,5): error MSB3021: Unable to copy file "/var/tmp/portage/games-arcade/osu-lazer-2021.820.0/homedir/.nuget/packages/ppy.osu.game.resources/2021.820.0/lib/netstandard2.1/pt-br/osu.Game.Resources.resources.dll" to "bin/Release/net5.0/linux-x64/pt-br/osu.Game.Resources.resources.dll". Could not find a part of the path '/var/tmp/portage/games-arcade/osu-lazer-2021.820.0/work/osu-2021.820.0/osu.Desktop/bin/Release/net5.0/linux-x64/pt-br/osu.Game.Resources.resources.dll'. [/var/tmp/portage/games-arcade/osu-lazer-2021.820.0/work/osu-2021.820.0/osu.Desktop/osu.Desktop.csproj]
>>> Source compiled.
 * Skipping make test/check due to ebuild restriction.
>>> Test phase [disabled because of RESTRICT=test]: games-arcade/osu-lazer-2021.820.0

>>> Install games-arcade/osu-lazer-2021.820.0 into /var/tmp/portage/games-arcade/osu-lazer-2021.820.0/image
 *
 * If the merge failed and you were getting any certificate related errors
 * please update net-misc/ca-certificates
 *
 * For more info related to this issue see:
 * https://github.com/NuGet/Announcements/issues/49
 *
Traceback (most recent call last):
  File "/usr/lib/portage/pypy3/doins.py", line 594, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/lib/portage/pypy3/doins.py", line 585, in main
    os.path.dirname(source)):
  File "/usr/lib/portage/pypy3/doins.py", line 434, in _doins
    return install_runner.install_file(source, os.path.dirname(dest))
  File "/usr/lib/portage/pypy3/doins.py", line 370, in install_file
    return self._ins_runner.run(source, dest_dir)
  File "/usr/lib/portage/pypy3/doins.py", line 179, in run
    sstat = os.stat(source)
FileNotFoundError: [Errno 2] No such file or directory: b'./osu.Desktop/bin/Release/netcoreapp5.0/linux-x64/*'
 * ERROR: games-arcade/osu-lazer-2021.820.0::molese failed (install phase):
 *   doins failed
 *
 * If you need support, post the output of `emerge --info '=games-arcade/osu-lazer-2021.820.0::molese'`,
 * the complete build log and the output of `emerge -pqv '=games-arcade/osu-lazer-2021.820.0::molese'`.
 * The complete build log is located at '/var/tmp/portage/games-arcade/osu-lazer-2021.820.0/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/games-arcade/osu-lazer-2021.820.0/temp/environment'.
 * Working directory: '/var/tmp/portage/games-arcade/osu-lazer-2021.820.0/work/osu-2021.820.0'
 * S: '/var/tmp/portage/games-arcade/osu-lazer-2021.820.0/work/osu-2021.820.0'
```

**Comment by m0lese** [comment]
Solution for now: 9b450787f93b12297345dcba7102cd42ecc42e99
